# Generated by Django 3.2 on 2026-09-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20260915_0908'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(
                condition=models.Q(withdrawal__isnull=False),
                fields=('withdrawal', 'type'),
                name='unique_transaction_withdrawal_type',
            ),
        ),
    ]
